/*
 *  Copyright (c) 2025 twinlife SA.
 *  SPDX-License-Identifier: AGPL-3.0-only
 *
 *  Contributors:
 *   Romain Kolb (romain.kolb@skyrock.com)
 */

#import "TLOnGetAllBackupsIQ.h"

#import "TLDecoder.h"
#import "TLEncoder.h"

/**
 * Response IQ for GetAllBackupsIQ, contains info about all backups generated by this account.
 * <p>
 * Schema version 1
 * <pre>
 * {
 *  "schemaId":"088b1c90-f9ea-4d1b-8be3-00d6e9b3afe8",
 *  "schemaVersion":"1",
 *
 *  "type":"record",
 *  "name":"OnGetAllBackupsIQ",
 *  "namespace":"org.twinlife.schemas.account",
 *  "super":"org.twinlife.schemas.BinaryPacketIQ"
 *  "fields": [
 *  {"name":"backups", [
 *         {"name":"id", "type": "uuid",
 *          "name": "creationDate", "type": "long"
 *         }
 *      ]}
 *  ]
 * }
 *
 * </pre>
 */

//
// Implementation: TLOnGetAllBackupsIQSerializer
//

@interface TLOnGetAllBackupsIQ ()
- (instancetype) initWithSerializer:(TLBinaryPacketIQSerializer *)serializer iq:(TLBinaryPacketIQ *)iq backups:(NSArray<TLBackupInfo *> *)backups;
@end

@implementation TLOnGetAllBackupsIQSerializer

- (nonnull instancetype)initWithSchema:(nonnull NSString *)schema schemaVersion:(int)schemaVersion {

    return [super initWithSchema:schema schemaVersion:schemaVersion class:[TLOnGetAllBackupsIQ class]];
}

- (void)serializeWithSerializerFactory:(TLSerializerFactory *)serializerFactory encoder:(id<TLEncoder>)encoder object:(NSObject *)object {

    @throw [NSException exceptionWithName:@"TLEncoderException" reason:nil userInfo:nil];
}

- (NSObject *)deserializeWithSerializerFactory:(TLSerializerFactory *)serializerFactory decoder:(id<TLDecoder>)decoder {
    
    TLBinaryPacketIQ *iq = (TLBinaryPacketIQ *)[super deserializeWithSerializerFactory:serializerFactory decoder:decoder];
    
    int size = [decoder readInt];
    NSMutableArray<TLBackupInfo *> *backups = [[NSMutableArray alloc] initWithCapacity:size];

    for (int i = 0; i < size; i++) {
        TLBackupInfo *backup = [[TLBackupInfo alloc] initWithUUID:[decoder readUUID] creationDate:[decoder readLong]];
        [backups addObject:backup];
    }
    
    return [[TLOnGetAllBackupsIQ alloc] initWithSerializer:self iq:iq backups:backups];
}

@end

//
// Implementation: TLOnGetAllBackupsIQ
//

@implementation TLOnGetAllBackupsIQ

- (nonnull instancetype)initWithSerializer:(nonnull TLBinaryPacketIQSerializer *)serializer iq:(nonnull TLBinaryPacketIQ *)iq backups:(nonnull NSArray<TLBackupInfo *> *)backups {

    self = [super initWithSerializer:serializer iq:iq];
    
    if (self) {
        _backups = backups;
    }
    return self;
}

@end
